on:
  issues:
    types: [opened]
jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
        - name: greetings
          uses: urcomputeringpal/add-remove-labels-action@master
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            action: add
            labels: greetings
